# Generated by Django 5.0.1 on 2024-01-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
