# Generated by Django 5.0.1 on 2024-01-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_order_previous_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='tracking_number',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True, unique=True),
        ),
    ]
