# Generated by Django 5.0.1 on 2024-01-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypersonprofile',
            name='profile_picture',
            field=models.ImageField(upload_to='delivery-profile-pictures'),
        ),
    ]
