# Generated by Django 5.0.1 on 2024-01-13 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_deliverypersonprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customersprofile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
